// This file is generated by scripts/generate-transition-assets.mjs.
// PNG IHDR dimensions are read from public/transition on every dev/build startup.

export type TransitionAsset = {
  id: string;
  src: string;
  width: number;
  height: number;
  kind: "primary" | "secondary";
};

export const transitionAssets = [
  {
    "id": "almond-1",
    "src": "/transition/almonds/almond-1.png",
    "width": 120,
    "height": 147,
    "kind": "primary"
  },
  {
    "id": "almond-2",
    "src": "/transition/almonds/almond-2.png",
    "width": 120,
    "height": 147,
    "kind": "primary"
  },
  {
    "id": "almond-3",
    "src": "/transition/almonds/almond-3.png",
    "width": 120,
    "height": 147,
    "kind": "primary"
  },
  {
    "id": "almond-4",
    "src": "/transition/almonds/almond-4.png",
    "width": 120,
    "height": 147,
    "kind": "primary"
  },
  {
    "id": "cashew-1",
    "src": "/transition/cashew/cashew-1.png",
    "width": 120,
    "height": 78,
    "kind": "primary"
  },
  {
    "id": "cashew-2",
    "src": "/transition/cashew/cashew-2.png",
    "width": 120,
    "height": 78,
    "kind": "primary"
  },
  {
    "id": "cashew-3",
    "src": "/transition/cashew/cashew-3.png",
    "width": 120,
    "height": 109,
    "kind": "primary"
  },
  {
    "id": "cashew-4",
    "src": "/transition/cashew/cashew-4.png",
    "width": 120,
    "height": 109,
    "kind": "primary"
  },
  {
    "id": "pistachio-1",
    "src": "/transition/pistachio/pistachio-1.png",
    "width": 135,
    "height": 113,
    "kind": "primary"
  },
  {
    "id": "pistachio-2",
    "src": "/transition/pistachio/pistachio-2.png",
    "width": 125,
    "height": 105,
    "kind": "primary"
  },
  {
    "id": "pistachio-3",
    "src": "/transition/pistachio/pistachio-3.png",
    "width": 145,
    "height": 89,
    "kind": "primary"
  },
  {
    "id": "pistachio-4",
    "src": "/transition/pistachio/pistachio-4.png",
    "width": 135,
    "height": 101,
    "kind": "primary"
  },
  {
    "id": "pumpkin-seed-1",
    "src": "/transition/pumpkin-seed/pumpkin-seed-1.png",
    "width": 68,
    "height": 89,
    "kind": "secondary"
  },
  {
    "id": "pumpkin-seed-2",
    "src": "/transition/pumpkin-seed/pumpkin-seed-2.png",
    "width": 99,
    "height": 61,
    "kind": "secondary"
  },
  {
    "id": "pumpkin-seed-3",
    "src": "/transition/pumpkin-seed/pumpkin-seed-3.png",
    "width": 99,
    "height": 61,
    "kind": "secondary"
  },
  {
    "id": "pumpkin-seed-4",
    "src": "/transition/pumpkin-seed/pumpkin-seed-4.png",
    "width": 68,
    "height": 89,
    "kind": "secondary"
  },
  {
    "id": "raisin-1",
    "src": "/transition/raisin/raisin-1.png",
    "width": 47,
    "height": 59,
    "kind": "secondary"
  },
  {
    "id": "raisin-2",
    "src": "/transition/raisin/raisin-2.png",
    "width": 47,
    "height": 59,
    "kind": "secondary"
  },
  {
    "id": "raisin-3",
    "src": "/transition/raisin/raisin-3.png",
    "width": 70,
    "height": 58,
    "kind": "secondary"
  },
  {
    "id": "raisin-4",
    "src": "/transition/raisin/raisin-4.png",
    "width": 70,
    "height": 58,
    "kind": "secondary"
  },
  {
    "id": "cranberry-1",
    "src": "/transition/cranberry/cranberry-1.png",
    "width": 40,
    "height": 37,
    "kind": "secondary"
  },
  {
    "id": "cranberry-2",
    "src": "/transition/cranberry/cranberry-2.png",
    "width": 47,
    "height": 45,
    "kind": "secondary"
  },
  {
    "id": "cranberry-3",
    "src": "/transition/cranberry/cranberry-3.png",
    "width": 49,
    "height": 44,
    "kind": "secondary"
  },
  {
    "id": "cranberry-4",
    "src": "/transition/cranberry/cranberry-4.png",
    "width": 47,
    "height": 39,
    "kind": "secondary"
  }
] as const satisfies readonly TransitionAsset[];

export const primaryIngredients = transitionAssets.filter((asset) => asset.kind === "primary");
export const secondaryIngredients = transitionAssets.filter((asset) => asset.kind === "secondary");
